### PR TITLE
increment lineCount before lineCount is checked

### PR DESCRIPTION
**Pull request by stevenmathews**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
can I have some context about why?

**Comment by stevenmathews** [comment]
Didn't work for me otherwise

**Comment by kalinchernev** [comment]
@stevenmathews share some more details please if a change is actually intended?

**Comment by ccarruitero** [comment]
Thanks @stevenmathews for your PR, but the solution is working correctly.

I'm going to close since this it's stale from a lot of time ago. Feel free to open a new PR or an issue if you found any problem.

**Pull request closed without merging**
