### PR TITLE
fix http_server problem (use full input on every retry)

### PR DESCRIPTION
**Pull request by JasonWoof**
My solution for the http_server problem fails almost all the time because of a bug in the stream-adventure codebase's tester that makes it fail to send the first word of input over http most of the time.

This is presumably because of a race condition, and that the retry code doesn't re-send words that tried to send to a past (failed) connection.

My patch fixes the retry code so that it passes all the words on every try.

### CODE REVIEW

**Comment by JasonWoof** [comment]
P.S. I wrote the following:

	var net = require('net');

	var server = net.createServer(function(socket) {
		socket.pipe(process.stdout);
		setTimeout(function() {
			socket.end('HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-length: 3\r\n\r\nhi\n'
	);
		}, 520);
	});

	server.listen(Number(process.argv[2]), '127.0.0.1');

This was used to verify that the stream-adventure verify script was not passing the first word to my code at all.

**Comment by JasonWoof** [comment]
If your computer is to fast to reproduce this bug, you should be able to trigger this bug by putting a 60ms delay in your solution.

**Comment by kalinchernev** [comment]
Possibly related to testing framework in overall #168

**Comment by ccarruitero** [comment]
@JasonWoof thanks for take the time on make this PR.

We refactored the problems to use `workshopper-exercise` in https://github.com/workshopper/stream-adventure/commit/35db979e60172b4573c4a12104e10bd48fcc5b1b, so this couldn't be merged.

**Pull request closed without merging**
